dist: trusty
language: java
install: skip

jdk: oraclejdk8

script: "./gradlew clean build" # gradle build runs test

before_deploy:
  - ./gradlew clean
  - ./gradlew jar
  - git config --local user.name "Patrik FORTIER"
  - git config --local user.email "patrik.fortier@insa-lyon.fr"
  - export TAG="$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - git tag $TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "app/build/libs/*"
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    jdk: oraclejdk8