dist: trusty
language: java
install: skip
jdk: oraclejdk8

script:
  - ./gradlew jar

deploy:
  provider: releases
  api_key: "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"
  file: "app/build/libs/app.jar"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
