dist: trusty
language: java
install: skip

jdk: oraclejdk8

script: "./gradlew clean build" # gradle build runs test

before_deploy:
  - ./gradlew clean
  - ./gradlew jar
  - git config --local user.name "Patrik FORTIER"
  - git config --local user.email "patrik.fortier@insa-lyon.fr"
  - export NAME="v$(./gradlew version -q)"
  - git tag $NAME

deploy:
  provider: releases
  api_key: "GH_TOKEN"
  file_glob: true
  file: "app/build/libs/*"
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    jdk: oraclejdk8