dist: trusty
language: java
install: skip
jdk: oraclejdk8

script:
  - ./gradlew jar

deploy:
  provider: releases
  file: "app/build/libs/app.jar"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
